analytics: {}
color:
  brandColors:
    - '#D0C8A8'
    - '#201000'
    - '#908878'
    - '#C8B080'
    - '#E8E0C8'
  brandStrength: 1
  lightness: 1
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 0.2528
name: Lore Vanelslande
opengraph: {}
purpose: []
typography_spectrum: 0
