name: Lore Vanelslande
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23846
title: Geometrist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9d9d9'
    - '#bdbdbd'
    - '#959595'
    - '#656565'
    - '#1a1a1a'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
