name: Lore Vanelslande
favicon: null
layout_spectrum: 0.2528
typography_spectrum: 0
title: Lore Vanelslande
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9d9d9'
    - '#bdbdbd'
    - '#959595'
    - '#656565'
    - '#1a1a1a'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
