name: Lore Vanelslande
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75002
title: Geometrist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffcf5'
    - '#d8dfe5'
    - '#abaca4'
    - '#8a8b83'
    - '#747266'
  brandStrength: 0.5467961470130831
  lightness: 1
  saturation: 0.328468645690009
  rhythmicContrast: 0.0956034092232585
purpose: []
