name: Lore Vanelslande
favicon: null
layout_spectrum: 0.8187217814847827
typography_spectrum: 0.3741768749896437
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5467961470130831
  lightness: 0.47827124665491283
  saturation: 0.328468645690009
  rhythmicContrast: 0.0956034092232585
purpose: []
